### ISSUE TITLE
Initial security improvement checklist

### ISSUE THREAD

**Issue by dannysauer** [SUSE/skuba#1004]
We need to more formally document our security posture within a skuba-built CaaSP cluster.  Notes here until some decision is reached as to where this should go.

Goals:
 - [ ] identify user-facing security issues (concerns which should be documented for users to deal with)
 - [ ] identify developer-relevant security issues (concerns which should be handled internally)

High-level steps:
 - [ ] List components of cluster (default and optional)
 - [ ] Catalog overlay network topology
 - [ ] Determine attack surface (categorize threats based on trusted v/s untrusted users?)
 - [ ] Identify steps for reducing attack surface (developer checklist, CI tests, something else?)
 - [ ] Identify opportunities for monitoring cluster behavior (feeds into alerting on anomalies)
